Repository enjin/enjincraft, pull requests merged in 2020-07, with the labels that each got.

#57 Implement link permissions
  spigot/src/main/java/com/enjin/enjincraft/spigot/configuration/Conf.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/configuration/ConfPath.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/EnjPlayer.java
  spigot/src/main/resources/config.yml
Labels: enhancement

#66 Transitioned Fungible Tokens to Database
  spigot/src/main/java/com/enjin/enjincraft/spigot/SpigotBootstrap.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdToken.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/i18n/Translation.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/storage/Database.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/LegacyTokenConverter.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenManager.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenModel.java
  spigot/src/main/resources/db/token/CreateToken.sql
  spigot/src/main/resources/db/token/CreateTokenInstance.sql
  spigot/src/main/resources/db/token/DeleteToken.sql
  spigot/src/main/resources/db/token/DeleteTokenInstance.sql
  spigot/src/main/resources/db/token/GetAllTokens.sql
  spigot/src/main/resources/db/token/GetNBT.sql
  spigot/src/main/resources/db/token/GetToken.sql
  spigot/src/main/resources/db/token/SetupToken.sql
  spigot/src/main/resources/db/token/SetupTokenInstance.sql
  spigot/src/main/resources/db/token/SetupTokenPermission.sql
  spigot/src/main/resources/db/token/UpdateNBT.sql
  spigot/src/main/resources/db/token/UpdateToken.sql
  spigot/src/main/resources/db/token/UpdateTokenInstance.sql
Labels: enhancement

#67 Token importing
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdToken.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/i18n/Translation.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenManager.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenModel.java
Labels: enhancement, refactor

#70 Fix for trade invite message
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdTrade.java
Labels: bug

#69 Relocate NBT-API
  spigot/build.gradle
Labels: enhancement

#71 Addressed NullPointerException when clearing permission attachment
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/EnjPermissionAttachment.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/EnjPlayer.java
Labels: bug

#72 Updated NBT-API from 2.3.0 to 2.4.1
  build.gradle
Labels: bug

#73 Cleaned up code base
  spigot/src/main/java/com/enjin/enjincraft/spigot/AuthenticationTask.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/SpigotBootstrap.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdBalance.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdConf.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdDevSend.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdEnj.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdLink.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdQr.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdSend.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdToken.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdTrade.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdUnlink.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdWallet.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CommandContext.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/EnjCommand.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/SenderType.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/arg/LocaleArgumentProcessor.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/arg/PlayerArgumentProcessor.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/arg/TokenDefinitionArgumentProcessor.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/configuration/Conf.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/configuration/ConfPath.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/dependencies/Dependency.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/dependencies/DependencyConfig.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/dependencies/DependencyManager.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/enums/CommandProcess.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/enums/Permission.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/events/EnjPlayerQuitEvent.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/hooks/PlaceholderApiExpansion.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/i18n/Locale.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/i18n/Translation.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/listeners/EnjEventListener.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/listeners/QrItemListener.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/listeners/TokenItemListener.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/EnjPermissionAttachment.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/EnjPlayer.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/FetchQrImageTask.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/PlayerInitializationTask.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/player/PlayerManager.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/storage/Database.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/LegacyTokenConverter.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenManager.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenModel.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenPermission.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/token/TokenPermissionGraph.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/trade/TradeManager.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/trade/TradeSession.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/trade/TradeUpdateTask.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/trade/TradeView.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/trade/UnregisterTradeInviteException.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/util/TokenUtils.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/util/UiUtils.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/wallet/TokenWallet.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/wallet/TokenWalletView.java
Labels: refactor

#75 Change dev config value from identity id to eth address.
  spigot/src/main/java/com/enjin/enjincraft/spigot/SpigotBootstrap.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/cmd/CmdDevSend.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/configuration/Conf.java
  spigot/src/main/java/com/enjin/enjincraft/spigot/configuration/ConfPath.java
  spigot/src/main/resources/config.yml
Labels: enhancement
